version: "3.8"

services:
  muas-ghost:
    #image: ghost:5.80.1
    image: ghost:latest
    environment:
      url: https://muas.facil.co.kr

      database__client: mysql
      database__connection__host: db_mysql
      database__connection__port: 3306
      database__connection__user: ragoni
      database__connection__database: muas

    secrets:
      - mysql_password

    # ✅ secret 파일을 읽어 password 문자열로 주입
    command: >
      sh -lc '
        export database__connection__password="$$(cat /run/secrets/mysql_password)";
        cp /custom/config.production.json /var/lib/ghost/config.production.json;
        docker-entrypoint.sh node current/index.js
      '

    volumes:
      - /docker/muas/content:/var/lib/ghost/content
      - /docker/muas/config.production.json:/custom/config.production.json

    networks:
      - proxy
      - dbnet

    deploy:
      replicas: 1
      placement:
        constraints:
          #- node.hostname == gram
          - node.role == worker

      labels:
        - "caddy=muas.facil.co.kr"
        - "caddy.reverse_proxy={{upstreams 2368}}"
        - "caddy.tls.dns=cloudflare"
        - "caddy.tls.ca=https://acme-v02.api.letsencrypt.org/directory"

  tech-ghost:
    image: ghost:latest

    environment:
      url: https://tech.facil.co.kr

      database__client: mysql
      database__connection__host: db_mysql
      database__connection__port: 3306
      database__connection__user: ragoni
      database__connection__database: tech

    secrets:
      - mysql_password

    command: >
      sh -lc '
        export database__connection__password="$$(cat /run/secrets/mysql_password)";
        cp /custom/config.production.json /var/lib/ghost/config.production.json;
        docker-entrypoint.sh node current/index.js
      '

    volumes:
      - /docker/tech/content:/var/lib/ghost/content
      - /docker/tech/config.production.json:/custom/config.production.json

    networks:
      - proxy
      - dbnet

    deploy:
      placement:
        constraints:
          #- node.hostname == gram
          - node.role == worker

      labels:
        - "caddy=tech.facil.co.kr"
        - "caddy.reverse_proxy={{upstreams 2368}}"
        - "caddy.tls.dns=cloudflare"
        - "caddy.tls.ca=https://acme-v02.api.letsencrypt.org/directory"

  blog-wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db_mysql:3306
      WORDPRESS_DB_USER: ragoni
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      WORDPRESS_DB_NAME: blog
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_PREFIX', 'blog_');   # key prefix로 충돌 방지

    secrets:
      - mysql_password
    networks:
      - proxy
      - dbnet
    deploy:
      placement:
        constraints:
          - node.role == worker
          #- node.hostname == gram
      labels:
        - "traefik.enable=true"
        - "caddy=blog.facil.co.kr"
        - "caddy.reverse_proxy={{upstreams 80}}"
        - "caddy.tls.dns=cloudflare"
        - "caddy.tls.ca=https://acme-v02.api.letsencrypt.org/directory"

    volumes:
      - /docker/blog/:/var/www/html
      - /docker/word/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini


networks:
  proxy:
    external: true
  dbnet:
    external: true

secrets:
  mysql_password:
    external: true

