version: "3.8"

services:
  mysql:
    image: mysql:8.0
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ragoni
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - /DB/mysql:/var/lib/mysql
    networks:
      - dbnet
    deploy:
      placement:
        constraints:
          #- node.role == worker
          #- node.hostname == pubuntu
          - node.hostname == gram
      endpoint_mode: dnsrr
      restart_policy:
       condition: any
       delay: 5s

    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - dbnet
    deploy:
      placement:
        constraints:
          #- node.hostname == pubuntu
          - node.hostname == gram
          #- node.role == worker
  postgres:
    image: postgres:16
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ragoni
      POSTGRES_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    volumes:
      - /DB/postgres:/var/lib/postgresql/data
    networks:
      - dbnet
    deploy:
      placement:
        constraints:
          #- node.hostname == pubuntu
          - node.hostname == gram
          #- node.role == worker
          
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    networks:
      - proxy
      - dbnet
    volumes:
      # CloudBeaver workspace (설정/유저/연결정보 등 저장)
      - /docker/cloudb:/opt/cloudbeaver/workspace

    environment:
      - TZ=Asia/Seoul

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == gram
          #- node.hostname == pubuntu
      labels:
        # ✅ Caddy (caddy-docker-proxy) 라벨
        - "caddy=db.facil.co.kr"
        - "caddy.reverse_proxy={{upstreams 8978}}"

        # (선택) 압축
        - "caddy.encode=zstd gzip"

        # (선택) 기본 인증 걸고 싶으면 아래 1줄만 활성화
        - "caddy.basicauth=/* admin $2a$14$gGEAkKDX0IKljp./D0ySxOkbdwJoaI5KAx5BQbR1dS0XMtOYHqzVC"

networks:
  proxy:
    external: true
  dbnet:
    external: true

secrets:
  mysql_password:
    external: true
  mysql_root_password:
    external: true
