version: "3.8"
services:
  uljubot:
    image: ciong/uljubot:latest
    volumes:
      - /docker/data:/app/web/instance
      - /docker/logs:/app/logs
    environment:
      - TZ=Asia/Seoul
      - MAX_WAIT_MINUTES=20
      - PRE_LOGIN_MINUTES=10
        #    secrets:
        #- uljubot_secret_key
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == gram
      labels:
        - "caddy=uljubot.facil.co.kr"
        - "caddy.reverse_proxy={{upstreams 5000}}"


          #secrets:
          # uljubot_secret_key:
          #external: true

networks:
  proxy:
    external: true
