version: "3.8"

services:
  watcher:
    image: ciong/ulju-watcher:latest
    env_file:
      - /docker/ulju_watcher/.env
    volumes:
      #- /mnt/ssh_samba/sync:/mnt/ssh_samba/sync
      - /mnt/main:/mnt/ssh_samba/sync
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager   # ⬅ 매니저 노드에만 배포
          #- node.hostname == blue
